apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: ghcr.io/heymikeey/hello-world/hello-world:v5.0.0
        name: hello-world
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pod-info-volume
          mountPath: /usr/share/nginx/html/pod-name.txt
          subPath: pod-name.txt
        - name: node-info-volume
        mountPath: /usr/share/nginx/html/node-name.txt
        subPath: node-name.txt
      volumes:
      - name: pod-info-volume
        downwardAPI:
          items:
            - path: "pod-name.txt"
              fieldRef:
                fieldPath: metadata.name
      - name: node-info-volume
        downwardAPI:
          items:
            - path: "node-name.txt"
              fieldRef:
                fieldPath: spec.nodeName  # Node name
